spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        default_schema: course
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    schemas: course
    locations: classpath:db/migration
    baseline-on-migrate: true
